[package]
name = "klyhostservice"
version = "0.1.0"
authors = ["walker"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clip = "0.1"
log = "0.4"
log4rs = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
lazy_static = "1.4"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"
lto = false

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true