refresh_rate: 5 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%f%Z)} [{t}] {l} {P} {I} {M}:{f}:{L}:{m}{n}"
  log_file:
    kind: rolling_file
    path: "log/klyhostservice.log"
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%f%Z)} [{t}] {l} {P} {I} {M}:{f}:{L}:{m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        pattern: "log/klyhostservice-{}.log"
        base: 0
        count: 10

root:
  level: info
  appenders:
    - stdout
    - log_file

loggers:
  klyhostservice::lib:
    level: info
    appenders:
      - log_file
    additive: false